SELECT *
  FROM [OLSS_MFAPPL_PRD]..[OLSS_MFAPPL].[TB_INVOICENUMBER]
  where AGREEMENTNUMBER = '0000672/4/01/03/2021'
  --endperiod = '2021-05-30'
  order by ENDPERIOD

  SELECT *  FROM [OLSS_MFAPPL_PRD]..[OLSS_MFAPPL].[RECON_AGREEMENT] where AGREEMENTNUMBER like '%503/4/01%'
  SELECT *  FROM [OLSS_MFAPPL_PRD]..[OLSS_MFAPPL].[RECON_DETAIL_SCHEDULES] where AGREEMENTNUMBER = '0000464/4/01/04/2020'
  SELECT *  FROM [OLSS_MFAPPL_PRD]..[OLSS_MFAPPL].[RECON_DETAIL_SCHEDULES_MERGE]
  SELECT *  FROM [OLSS_MFAPPL_PRD]..[OLSS_MFAPPL].[RECON_FINANCED_OBJECTS] where AGREEMENTNUMBER = '0000464/4/01/04/2020'
  SELECT *  FROM [OLSS_MFAPPL_PRD]..[OLSS_MFAPPL].[RECON_PAYMENT_SCHEDULES] where AGREEMENTNUMBER = '0000464/4/01/04/2020'
  SELECT *  FROM [OLSS_MFAPPL_PRD]..[OLSS_MFAPPL].[RECON_SKD] where SKD_NUMBER = '0000557/4/01/07/2020'
  SELECT *  FROM [OLSS_MFAPPL_PRD]..[OLSS_MFAPPL].[RECON_SKD_DETAIL] 
  SELECT *  FROM [OLSS_MFAPPL_PRD]..[OLSS_MFAPPL].[OPLBASICCONDITION] 

  SELECT *
  FROM [OLSS_MFAPPL_PRD]..[OLSS_MFAPPL].[TB_INVOICENUMBER]
  where AGREEMENTNUMBER = '0000249/4/10/08/2019'
  order by ENDPERIOD
    SELECT *
  FROM [OLSS_MFAPPL_PRD]..[OLSS_MFAPPL].[TB_INVOICENUMBER]
  where AGREEMENTNUMBER = '0000614/4/01/01/2021'
  order by ENDPERIOD

SELECT *
  FROM [OLSS_MFAPPL_PRD]..[OLSS_MFAPPL].[TB_BIL_PAYSCHEDULE]
  where AGREEMENTNUMBER = '0000016/4/17/01/2017'
  
SELECT *--idtb_bil_payscheduledtl, idtb_bil_payschedule, paymentschedule, billingamt, expectationcollectionamount, startperiod, endperiod
  FROM [OLSS_MFAPPL_PRD]..[OLSS_MFAPPL].[TB_BIL_PAYSCHEDULEDTL]
  WHERE IDTB_BIL_PAYSCHEDULE in (9000299)
  order by paymentschedule
  
 q

 SELECT  A.* FROM OPENQUERY(OLSS_MFAPPL_PRD, 'SELECT * FROM AGREEMENT_STATUS') A 
 WHERE A.AGREEMENT_ID IN ('0000028/4/03/12/2020','0000029/4/03/01/2021')

select a.AGREEMENTNUMBER, a.* from openquery(OLSS_MFAPPL_PRD, 'select * from TB_BIL_PAYMENTHISTORY') a 
where a.AGREEMENTNUMBER like '0000016/4/17/01/2017'  and a.TRXCODE='PAY' ORDER BY DUE_DATE





  SELECT *
  FROM [OLSS_MFAPPL_PRD]..[OLSS_MFAPPL].[TB_BIL_PAYSCHEDULE] WHERE IDOPLAGREEMENT = '1444'

  SELECT *
  FROM [OLSS_MFAPPL_PRD]..[OLSS_MFAPPL].[ASSET_SELLING_STG]

  SELECT * FROM [OLSS_MFAPPL_PRD]..[OLSS_MFAPPL].[OPLAGREEMENT] WHERE AGREEMENTNUMBER = '0000505/4/01/08/2020'

  SELECT * FROM  [OLSS_MFAPPL_PRD]..[OLSS_MFAPPL].[TB_MKT_SKD] WHERE SKDNO = '0000557/4/01/07/2020'
  SELECT * FROM  [OLSS_MFAPPL_PRD]..[OLSS_MFAPPL].[TB_MKT_SKD] WHERE SKDNO = '0000557/4/01/07/2020'

  SELECT * FROM [OLSS_MFAPPL_PRD]..[OLSS_MFAPPL].[OPLUOBJECTLEASE] WHERE AGREEMENTNUMBER LIKE '%517/4/01%'

  SELECT * FROM [OLSS_MFAPPL_PRD]..[OLSS_MFAPPL].[OPLCALCULATION] WHERE OPLCALCULATIONNUMBER = '00221/OCN/01/07/2020'